defaults: &defaults
  BLOG_USERNAME: "willis"
  BLOG_PASSWORD: "plummer"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  BLOG_USERNAME: ENV['my_admin_username']
  BLOG_PASSWORD: ENV['my_admin_password']
